SELECT *
FROM CITY
WHERE COUNTRYCODE = "USA" AND POPULATION > 100000;

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = "USA" AND POPULATION > 120000;

SELECT *
FROM CITY;

SELECT *
FROM CITY
WHERE ID = 1661;

SELECT *
FROM CITY
WHERE COUNTRYCODE = "JPN";

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = "JPN";

SELECT CITY, STATE
FROM STATION;

SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

SELECT count(CITY) - count(DISTINCT CITY)
FROM STATION;

SELECT CITY, char_length(CITY)
FROM (
    SELECT CITY, 
        RANK() OVER(ORDER BY char_length(CITY) DESC, CITY) AS rank_long,
        RANK() OVER(ORDER BY char_length(CITY), CITY) AS rank_short
    FROM STATION
) AS CITY_RANK
WHERE CITY_RANK.rank_short = 1 OR CITY_RANK.rank_long = 1;

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("^a|^e|^i|^o|^u");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("a$|e$|i$|o$|u$");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("[aeiouAEIOU]$") AND CITY REGEXP ("^[aeiouAEIOU]");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("^[^aeiouAEIOU]");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("[^aeiouAEIOU$]");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("^[^aeiouAEIOU]") OR CITY REGEXP ("[^aeiouAEIOU]$");

SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP ("^[^aeiouAEIOU]") AND CITY REGEXP ("[^aeiouAEIOU]$");

SELECT NAME
FROM STUDENTS
WHERE MARKS > 75
ORDER BY SUBSTR(NAME, -3), ID;

SELECT name
FROM Employee 
ORDER BY NAME;